version: "3.8"

services:
  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: oracle_itsupport
    ports:
      - "1521:1521"
    environment:
      - ORACLE_DATABASE=ItSupport
      - ORACLE_PASSWORD=admin
      - APP_USER=admin
      - APP_USER_PASSWORD=admin
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s admin/admin@//localhost:1521/ItSupport" ]
      interval: 30s
      timeout: 10s
      retries: 10

  backend:
    build: .
    container_name: it-support-backend
    depends_on:
      oracle:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521/ItSupport
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.Oracle12cDialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network

volumes:
  oracle_data:

networks:
  app-network:
    driver: bridge
