services:
  oracle:
    image: gvenzl/oracle-xe:latest
    container_name: oracle_itsupport
    ports:
      - "1521:1521"
    environment:
      - ORACLE_DATABASE=ItSupport
      - ORACLE_PASSWORD=admin
      - APP_USER=admin
      - APP_USER_PASSWORD=admin
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data: